### PR TITLE
Expanded Travis' testing matrix, streamlining dependencies

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open the build fails on PHP 5.4 no matter what I do - it's too slow to resolve and download the dependecies. Adding `-vvv` and `--profile` did not work, it simply hangs on downloading one of the packages.

**Comment by szymach** [comment]
@fsi-open locked down stable dependencies

**Comment by chives** [comment]
:+1:

**Comment by JarekW** [comment]
:+1:

**Comment by szymach** [comment]
@rn0

**Comment by rn0** [comment]
:+1:

**Pull request merged**
