### PR TITLE
Show value from default locale in text and fsi_removable_file forms

### PR DESCRIPTION
**Pull request by chives**
This PR requires https://github.com/fsi-open/doctrine-extensions-bundle/pull/49 and ``v1.1.3`` tag on https://github.com/fsi-open/doctrine-extensions-bundle

### CODE REVIEW

**Comment by chives** [comment]
@fsi-open now it also requires https://github.com/fsi-open/admin-bundle/pull/187 to merged first

**Comment by chives** [comment]
The build will pass after merging and tagging of https://github.com/fsi-open/doctrine-extensions/pull/55

**Comment by chives** [comment]
@fsi-open

**Comment by JarekW** [comment]
it's still [WIP] ?

**Comment by chives** [comment]
@JarekW nope

**Comment by chives** [comment]
@fsi-open

**Comment by szymach** [comment]
:+1:

**Comment by rn0** [comment]
:+1:

**Comment by JarekW** [comment]
:+1:

**Pull request merged**
