### PR TITLE
Removed usage of deprecated features

### PR DESCRIPTION
**Pull request by chives**

### CODE REVIEW

**Comment by chives** [comment]
@fsi-open

**Comment by JarekW** [comment]
i think in composer.json there should be now:
"fsi/doctrine-extensions-bundle": "~1.1,>=1.1.**4**"

**Comment by chives** [comment]
i've added dependency from ``symfony/options-resolver`` ~2.6 instead

**Comment by szymach** [comment]
:+1:

**Comment by rn0** [comment]
:+1:

**Pull request merged**
