### PR TITLE
Fixed wrong template option in list element, add missing event dispatcher call

### LINKED ISSUE #50: remove map-builder service from services.xml
remove [map-builder](https://github.com/fsi-open/admin-translatable-bundle/blob/master/Resources/config/services.xml#L16) as it [is defined already](https://github.com/fsi-open/admin-translatable-bundle/blob/master/Resources/config/context/resource.xml#L27)

### PR DESCRIPTION
**Pull request by szymach**
Resolves #50 and #55

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Comment by chives** [comment]
I'd rather add compiler pass in https://github.com/fsi-open/admin-bundle which adds call to `setEventDispatcher` to every service tagged with `event_dispatcher_aware`. This would not require adding any logic neither to this bundle nor to any bundle based on admin-bundle and requiring own controllers with event dispatcher.

**Comment by szymach** [comment]
Closed in favour of #57

**Pull request closed without merging**
