### PR TITLE
Fix for translatable forms using model transformers

### PR DESCRIPTION
**Pull request by chives**

### CODE REVIEW

**Comment by chives** [comment]
@fsi-open

**Comment by szymach** [comment]
:+1:

**Comment by JarekW** [comment]
Why normalized data is different from model data? It is equal to ViewData?

**Comment by chives** [comment]
``Form::getData()`` returns model data which may differ from normalized data when some model transformer is being used. Normalized data is the one which is mapped to form through property paths so this extension should refer to normalized data instead of model data.

**Comment by JarekW** [comment]
ok, :+1:

**Pull request merged**
